### ISSUE TITLE
use cases

### ISSUE THREAD

**Issue by ctb** [dcppc/2018-may-workshop#11]
we should have a use case fest!

this could involve:
* going through use case [glossary](https://docs.google.com/document/d/1-Xz6yQtmGdNZPRNOC_mnQFgwf18nVeLRQHgp0fFXoas/edit) and [template](https://docs.google.com/document/d/1WCTxwD3-to6yuoCxDRqIa7oER8GmlnnxxNtW2RY9W3U/edit#heading=h.cv4ml1vhly3)
* repeating/revisiting use case presentations from GTEx, TOPmed, and AGR;
* working on collating use cases from the KCs;
* editing/revising use cases for incorporation into the GitHub repo [design-guidelines](https://github.com/dcppc/design-guidelines)

**Comment by rossrepo** [comment]
I'm still relatively new to the DCPPC, so this would be extremely helpful since I don't know all of the use cases that have been decided on and why.
