### ISSUE TITLE
FAIRness scoring implications: KC touch points and user engagement

### ISSUE THREAD

**Issue by rossrepo** [dcppc/2018-may-workshop#17]
Repositive (Team Xenon, KC7) has an active user-base who have been keen to engage with any discussion concerning FAIRness scoring of data. We see FAIRness scores as an integral part of the metadata of digital objects with scores associated to GUIDs (KC2) and visible through the Commons APIs (KC3), portable workspaces (KC6) the search interface (KC7), and training and outreach (KC9). So, FAIRness and the method of scoring has implications across the KCs and we think this warrants an exploratory discussion. While we are looking forward to KC1’s overview of their thinking and progress on FAIRness scoring systems, it would also be great to explore some of the following FAIRness related topics:

1. Anticipating the impact of innovations of the FAIRness scoring approach over time in a full-stack environment
2. Granularity of FAIRness scoring of digital resources
3. Scientific community engagement i.e. starting with the user:
- Communicating to the scientific community the FAIRness scoring mechanism and what to do with community feedback
- Strategies to help researchers understand the value of FAIR data for both them and the scientific community using the Data Commons environment
- The role of the scientific community in either contributing to or qualifying FAIRness scores on an ongoing basis
- To show precedent for community engagement, some interesting links:
https://plaudit.pub/
http://octopus-hypothesis.netlify.com/
https://marvelapp.com/d4bd3ij/screen/42570995 (password: Octopus)

**Comment by AviMaayan** [comment]
@rossrepo This is exactly the direction we are heading toward in KC1. We have a new redesign of the FAIRshake system that we hope will be modular enough to accommodate integration with the full stacks and other efforts. You can review the presentations by @krobasky and @u8sand in the KC1 WG folder to get up to speed with these efforts: https://drive.google.com/drive/folders/1YEGyYKSru9f1eR_gQyn7mgy9RJbV7upf 
It would be great to interact and accelerate progress next week when we meet F2F.
