### ISSUE TITLE
Using GitHub PM repo to track concerns, blockers 

### ISSUE THREAD

**Issue by davissn30** [dcppc/2018-may-workshop#18]
Helium would like to discuss that possibility of using this repo's issues to note/track/solve concerns and blockers. (https://github.com/dcppc/project-management)

**Comment by ctb** [comment]
On Fri, May 25, 2018 at 10:50:12AM -0700, davissn30 wrote:
> Helium would like to discuss that possibility of using this repo's issues to note/track/solve concerns and blockers. (https://github.com/dcppc/project-management)

+1 from me
