### ISSUE TITLE
KC2 breakout session on May 30th afternoon

### ISSUE THREAD

**Issue by mercecrosas** [dcppc/2018-may-workshop#4]
The KC2 group would like to organize a breakout session to talk about KC products and demos on Thursday May 30th afternoon.

**Comment by danielskatz** [comment]
Does anyone have specific ideas on how to organize this session?

**Comment by raynamharris** [comment]
From an outside KC2 perspective, I think that depends on whether the goal is to brainstorm about future products and demos or to get feedback on work in progress. 

If it is the latter, you could organize a series of lightning talks and have a few people present to a large-ish audience, or you could go with a poster-session-like format where anyone who wants feedback on a demo can set up their laptop at a small table and the audience members walks around the room giving one-on-one feedback about demos.

**Comment by clarisca** [comment]
From the full stack perspective I'd like for the full stacks to describe their current approach/plan to identifiers and metadata. This would ignite some good discussions on what we should be doing next to enable interoperability. For instance,  I think there are a couple of "global id broker" services being developed within the consortium. Starting a discussion on how full stacks would interact with these brokers  is something that I'd like to see discussed at the workshop. What do you all think?

**Comment by mercecrosas** [comment]
I think that's a great idea @clarisca - are there representative of each full stack that could talk about this? It might be good to first describe the namespace registry and GUID brokers.

**Comment by clarisca** [comment]
@mercecrosas :  [All the full stack teams are attending the workshop. ](https://github.com/dcppc/2018-may-workshop/blob/master/attendees.md)


Other related topics are:

- GUID broker (s). I think there is more than one but I am unsure.
- bdbags/minid synergy
- Currently we are only considering the DATS metadata model which works well with GTEX. What about other datasets? 
- ...

**Comment by mercecrosas** [comment]
Thanks @clarisca

**Comment by zflamig** [comment]
Just chiming in here that Team Calcium would be interested in presenting their view and understanding more about how our GUIDs and resolution system can contribute to the pilot.
